# Étape 1 : build (avec TypeScript)
FROM node:20-bullseye AS builder

WORKDIR /app

# Copie des fichiers nécessaires à l'installation
COPY package.json package-lock.json ./

# Installation des dépendances
RUN npm install --legacy-peer-deps

# Copie du reste de l'application
COPY . .

# Génération build
RUN npm run build

# Étape 2 : dev runner allégé
FROM node:20-bullseye AS runner

WORKDIR /app

ENV NODE_ENV=dev

# Copie uniquement les fichiers nécessaires
COPY --from=builder /app/package.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/.env.example .env

COPY --from=builder /app/entrypoint.sh ./entrypoint.sh
RUN chmod +x entrypoint.sh

# Créer dossier de logs
RUN mkdir -p /app/logs

# Exposition du port
EXPOSE 9090

# Lancement
CMD ["./entrypoint.sh"]
